# Site wide configuration

title: Gareth Harman
locale: en_US
description: PhD Student Computational Biomedicine
logo: gh_circle.png
search: true
url: https://gareth-harman.github.io

# Jekyll configuration

comments: true
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-seo
  
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Gareth Harman
  avatar: bio-photo.jpg
  email: harmang@ohsu.edu
  disqus-shortname: #garethharman
  twitter: gareth_harman_
  facebook: #username
  github: gareth-harman
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: gareth-harman
  instagram: #username
  flickr: #username
  tumblr: #
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:  UA-151336770-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
